---
# tasks file for mytomrole
- include_tasks: mytominstall.yml
- include_tasks: mytomconfigfile.yml
- include_tasks: myadminpackages.yml
- include_tasks: mytomuser.yml
- include_tasks: mydeployjavaapp.yml